appone/urls.py
from django.conf.urls import url
from django.urls import path
from appone import views

app_name = "appone"
urlpatterns =[
    path('', views.index, name='index'),
    path('form/', views.form, name='form')
]

djangoProject1/urls.py
    # https://docs.djangoproject.com/en/3.2/topics/http/urls/

from django.contrib import admin
from django.urls import path
from django.conf.urls import include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('appone.urls')),


]

appone/models.py
from django.db import models


# Create your models here.
class Musician(models.Model):
    first_name = models.CharField(max_length=50, )
    last_name = models.CharField(max_length=50)
    instrument = models.CharField(max_length=100)

    def __str__(self):
        return self.first_name + " " + self.last_name


class Album(models.Model):
    artist = models.ForeignKey(Musician, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    release_date = models.DateField()

    rating = (
        (1, "Worst"),
        (2, "Bad"),
        (3, "Not Bad"),
        (4, "Good"),
        (5, "Excellent"),

    )

    num_stars = models.IntegerField(choices=rating)


def __str__(self):
    return self.name + ", Rating: " + str(self.num_stars)

appone/forms.py
from django import forms
from django.core import validators
from appone import models


class MusicianForm(forms.ModelForm):
    class Meta:
        model = models.Musician
        fields = "__all__"

# class user_form(forms.Form):
#     name = forms.CharField(validators=[validators.MaxLengthValidator(10), validators.MinLengthValidator(5)])
#     number_field = forms.IntegerField(validators=[validators.MaxValueValidator(15), validators.MinValueValidator(5)])

appone/views.py
from django.shortcuts import render
from django.http import HttpResponse

from appone.models import Musician, Album
from appone import forms


# Create your views here.


def index(request):
    musician_list = Musician.objects.order_by('first_name')
    diction = {'text_1': 'this is list of musicians, ', 'musician': musician_list}
    return render(request, 'first_app/index.html', context=diction)
    # return HttpResponse("<h1>I am from here</h1>")


def form(request):
    new_form = forms.MusicianForm()
    if request.method == 'POST':
        new_form = forms.MusicianForm(request.POST)

        if new_form.is_valid():
            new_form.save(commit=True)
            return index(request)

    diction = {'test_form': new_form, 'heading_1': 'Add New Musicians'}

    return render(request, 'first_app/form.html', context=diction)

templates/first_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

</body>
</html>

templates/first_app/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>this is from</title>
</head>
<body>


<h3>{{ heading_1 }}</h3>
<a href="{% url 'appone:index' %}">Back</a>
<form action="" method="post">
    {{ test_form.as_p }}
    {% csrf_token %}
    <input type="submit" name="submit" value="submit">

    <hr>

</body>
</html>

templates/first_app/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Musician LisT</title>


</head>
<body>
<h1>{{ text_1 }}</h1>
<a href="form.html/"></a>
<a href="{% url 'appone:form' %}">Add New</a>
<table border="1">
    <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>instrument Name</th>
    </tr>
    {% for row in musician %}
    <tr>
        <td>{{ row.first_name }}</td>
        <td>{{ row.last_name }}</td>
        <td>{{ row.instrument }}</td>
    </tr>
    {% endfor %}
</table>

</body>
</html>